name: Confrm Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        git clone https://github.com/catchorg/Catch2.git -b v2.x
        cd Catch2
        cmake -Bbuild -H. -DBUILD_TESTING=OFF
        sudo cmake --build build/ --target install
    - name: Run unit tests
      run: |
        cd ./test
        g++ ./unit_test_simple_json.cpp -o unit_test_simple_json
        ./unit_test_simple_json
